# Generated by Django 2.1.3 on 2018-11-23 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_info',
            fields=[
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='testapp.agent')),
                ('contactid', models.CharField(default=False, max_length=10)),
                ('mobileno', models.CharField(default=False, max_length=10)),
                ('email', models.CharField(default=False, max_length=10)),
                ('company',models.CharField(default=False,max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.CharField(max_length=21)),
                ('agent', models.CharField(max_length=50)),
                ('locname', models.CharField(max_length=40)),
                ('loccity', models.CharField(max_length=32)),
                ('pincode', models.IntegerField(max_length=10)),
            ],
        ),
    ]
