# Generated by Django 2.1.3 on 2018-11-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_contact_info_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='contactid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='email',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='mobileno',
            field=models.CharField(max_length=10),
        ),
    ]
