# Generated by Django 2.1.3 on 2018-11-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20181123_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='location',
        ),
    ]
