# Generated by Django 2.1.3 on 2018-11-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=30)),
                ('agent', models.CharField(max_length=40)),
                ('loc_name', models.CharField(max_length=40)),
                ('loc_city', models.CharField(max_length=10)),
                ('loc_state', models.CharField(max_length=40)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
