# Generated by Django 2.1.3 on 2018-11-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20181124_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_id',
            new_name='locationid',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='loc_city',
            new_name='loccity',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='loc_name',
            new_name='locname',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='loc_state',
            new_name='locstate',
        ),
        migrations.AddField(
            model_name='location',
            name='loc',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testapp.agent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='pincode',
            field=models.IntegerField(default=False),
        ),
    ]
