# Generated by Django 2.1.3 on 2018-11-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_info',
            name='agentid',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
