# Generated by Django 2.1.3 on 2018-11-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_contact_info_agentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_info',
            name='company',
        ),
    ]
