# Generated by Django 2.1.3 on 2018-11-29 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_auto_20181126_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_info',
            name='contactagent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='loc',
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='agentid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='testapp.agent'),
        ),
        migrations.AlterField(
            model_name='location',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.agent'),
        ),
    ]
