# Generated by Django 2.1.3 on 2018-11-29 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20181129_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='agentaddress',
        ),
        migrations.AlterField(
            model_name='address',
            name='agentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.agent'),
        ),
    ]
