# Generated by Django 2.1.3 on 2018-11-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20181129_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='agent',
            new_name='agentloc',
        ),
    ]
