# Generated by Django 5.0.3 on 2025-06-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.AlterField(
            model_name='address',
            name='addressid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
